#spring.application.name=send-email

spring:
  mail:
    host: smtp.gmail.com
    username: enockkimutai2004@gmail.com
    password: taur pjth yxmh kjqw
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true